import {useEffect,useRef,useState} from 'react';
import ShieldCheck from 'lucide-react/dist/esm/icons/shield-check.js';
import FileText from 'lucide-react/dist/esm/icons/file-text.js';
import Upload from 'lucide-react/dist/esm/icons/upload.js';
import Download from 'lucide-react/dist/esm/icons/download.js';
import CheckCircle2 from 'lucide-react/dist/esm/icons/circle-check.js';
import AlertTriangle from 'lucide-react/dist/esm/icons/triangle-alert.js';
import ChevronRight from 'lucide-react/dist/esm/icons/chevron-right.js';
import Save from 'lucide-react/dist/esm/icons/save.js';
import FolderOpen from 'lucide-react/dist/esm/icons/folder-open.js';
import Languages from 'lucide-react/dist/esm/icons/languages.js';
import Eye from 'lucide-react/dist/esm/icons/eye.js';
import Trash2 from 'lucide-react/dist/esm/icons/trash-2.js';
import Files from 'lucide-react/dist/esm/icons/files.js';
import ArrowRight from 'lucide-react/dist/esm/icons/arrow-right.js';
import X from 'lucide-react/dist/esm/icons/x.js';
import Sparkles from 'lucide-react/dist/esm/icons/sparkles.js';
import {assign,canAssign,duplicateGroups,emptyProject,exportChecklist,getBlockingIssues,getRequirementStatus,included,parsePages,removeFile,suggestMatches,totalPages,validateRequirements,withinLimits,type Language,type Project,type Status,type Stamp} from './domain';
import {dictionary,statusClass,en} from './i18n';
import {buildPackage,downloadBytes,inspectPdf,renderPreview} from './pdf';
import {saveWorkspace,restoreWorkspace} from './storage';
import {explainChecklist} from './ai';
type Message={key:keyof typeof en;name?:string};
const sampleNames=['01_financial_proposal.pdf','02_technical_proposal.pdf','03_tin_certificate.pdf','04_vat_certificate.pdf','bank_solvency.pdf','company_logo.png','experience_cert (1).pdf','experience_cert.pdf','scan_0042.pdf','trade_license_2025.pdf','trade_license_2026.pdf'];
function Preview({bytes,name,t,onClose}:{bytes:Uint8Array;name:string;t:typeof en;onClose:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),dialog=useRef<HTMLDialogElement>(null);const [page,setPage]=useState(1),[total,setTotal]=useState(1),[error,setError]=useState(false);
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 useEffect(()=>{let mounted=true;renderPreview(bytes,page,canvas.current!).then(n=>{if(mounted)setTotal(n);}).catch(()=>{if(mounted)setError(true);});return()=>{mounted=false;};},[bytes,page]);
 return <dialog ref={dialog} onCancel={onClose} aria-label={t.preview} className="preview-dialog"><div className="preview-head"><strong>{name}</strong><button onClick={onClose} aria-label={t.close}><X size={20}/></button></div><div className="preview-body">{error?<p role="alert">{t.badPDF}</p>:<canvas ref={canvas}/>}</div><div className="preview-nav"><button disabled={page<=1} onClick={()=>setPage(page-1)}>{t.previous}</button><span>{t.page} {page} {t.of} {total}</span><button disabled={page>=total} onClick={()=>setPage(page+1)}>{t.next}</button></div></dialog>;
}
export default function App(){
 const [lang,setLang]=useState<Language>(()=>localStorage.getItem('tenderready-language')==='bn'?'bn':'en');const t=dictionary(lang);
 const [p,setP]=useState<Project|null>(null),[busy,setBusy]=useState(false),[generating,setGenerating]=useState(false),[dirty,setDirty]=useState(false),[messages,setMessages]=useState<Message[]>([]),[preview,setPreview]=useState<{bytes:Uint8Array;name:string}|null>(null),[apiKey,setApiKey]=useState(''),[consent,setConsent]=useState(false),[aiBusy,setAiBusy]=useState(false),[aiText,setAiText]=useState('');const abort=useRef<AbortController|null>(null);
 const blocked=p?getBlockingIssues(p):[],selected=p?included(p):[],duplicates=p?duplicateGroups(p.files):[];const duplicateIds=new Set(duplicates.flat().map(f=>f.id));
 const counts:Record<Status,number>={'Missing':0,'Not provided':0,'Expiry date needed':0,'Expired':0,'OK':0};p?.requirements.forEach(r=>counts[getRequirementStatus(r,p.assignments[r.id],p.tender.submission_deadline)]++);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('tenderready-language',lang);},[lang]);
 const change=(next:Project)=>{setP(next);setDirty(true);};const notify=(key:keyof typeof en,name?:string)=>setMessages(m=>[...m.slice(-5),{key,name}]);
 const fail=(e:unknown,name?:string)=>{const k=e instanceof Error&&e.message in en?e.message as keyof typeof en:'error';notify(k,name);};
 const confirmReplace=()=>!p||!p.files.length&&!Object.keys(p.assignments).length||window.confirm(t.replace);
 async function importJSON(file:File){try{const x=validateRequirements(JSON.parse(await file.text()));if(confirmReplace()){change(emptyProject(x));notify('loaded');}}catch{notify('invalidJSON',file.name);}}
 async function ingest(files:File[],base:Project){setBusy(true);let next=base;for(const file of files){try{if(!/\.pdf$/i.test(file.name)){notify('notPDF',file.name);continue;}if(!withinLimits(next.files,file.size))throw Error('limitError');const accepted=await inspectPdf(file);next={...next,files:[...next.files,accepted]};setP(next);}catch(e){fail(e,file.name);}}setDirty(true);setBusy(false);return next;}
 async function sample(){if(!confirmReplace())return;setBusy(true);try{const response=await fetch('/sample/requirements.json');if(!response.ok)throw Error('invalidImport');const next=emptyProject(validateRequirements(await response.json()));const fs:File[]=[];for(const name of sampleNames){const r=await fetch('/sample/documents/'+encodeURIComponent(name));if(!r.ok)throw Error('error');fs.push(new File([await r.blob()],name,{type:name.endsWith('.pdf')?'application/pdf':'image/png'}));}setP(next);await ingest(fs,next);notify('sampleLoaded');}catch(e){fail(e);}finally{setBusy(false);}}
 function match(rid:string,fid:string){if(!p)return;try{change(assign(p,rid,fid));}catch(e){fail(e);}}
 async function generate(asPreview=false){if(!p||busy||generating||blocked.length)return;setGenerating(true);try{const bytes=await buildPackage(p);if(asPreview)setPreview({bytes,name:p.tender.tender_id+'_Package.pdf'});else{downloadBytes(bytes,p.tender.tender_id+'_Package.pdf','application/pdf');notify('done');}}catch(e){fail(e);}finally{setGenerating(false);}}
 async function stamp(file:File){if(!p)return;try{const bytes=new Uint8Array(await file.arrayBuffer());if(bytes[0]!==137||new TextDecoder().decode(bytes.slice(1,4))!=='PNG')throw Error('invalidPNG');const bitmap=await createImageBitmap(file);bitmap.close();change({...p,options:{...p.options,stamp:{bytes,pages:'',width:100,x:24,y:24,position:'bottom-right'}}});notify('stampReady');}catch{notify('invalidPNG');}}
 const updateStamp=(value:Partial<Stamp>)=>{if(p?.options.stamp)change({...p,options:{...p.options,stamp:{...p.options.stamp,...value}}});};
 const stampError=(()=>{if(!p?.options.stamp)return '';try{if(!parsePages(p.options.stamp.pages,totalPages(p)).length)return t.noStampPages;return '';}catch{return t.invalidPages;}})();
 async function askAI(){if(!apiKey||!consent){notify('aiRequired');return;}abort.current=new AbortController();const timer=setTimeout(()=>abort.current?.abort(),25000);setAiBusy(true);setAiText('');try{setAiText(await explainChecklist(apiKey,counts,lang,abort.current.signal));}catch{notify('aiError');}finally{clearTimeout(timer);setAiBusy(false);}}
 return <><a className="skip" href="#checklist">{t.skip}</a><header className="header"><div className="header-inner"><a className="brand" href="#" aria-label={t.home}><span className="brand-icon"><Files size={25}/></span><span>{t.brand}<small>{t.tagline}</small></span></a><div className="header-actions"><button className="language" onClick={()=>setLang(lang==='en'?'bn':'en')} aria-label="English / বাংলা"><Languages size={17}/>{lang==='en'?'বাংলা':'English'}</button><button aria-label={t.save} disabled={!p||busy||generating} onClick={async()=>{try{await saveWorkspace(p!);setDirty(false);notify('saved');}catch{notify('storageError');}}}><Save size={17}/><span>{t.save}</span></button><button aria-label={t.reopen} disabled={busy||generating} onClick={async()=>{try{const restored=await restoreWorkspace();if(confirmReplace()){setP(restored);setDirty(false);notify('restored');}}catch(e){fail(e);}}}><FolderOpen size={17}/><span>{t.reopen}</span></button></div></div></header>
 <main><div className="workspace-bar"><div className="steps"><span className={p?'complete':'active'}><b>01</b>{t.load}</span><ChevronRight size={16}/><span className={p?'active':''}><b>02</b>{t.check}</span><ChevronRight size={16}/><span><b>03</b>{t.download}</span></div><span className="privacy"><ShieldCheck size={15}/>{t.private}</span></div>
 <section className={'intro '+(p?'compact':'')}><div><span className="eyebrow">{p?t.tender:t.home}</span><h1>{p?p.tender.title:t.startTitle}</h1><p>{p?<><span className="tender-id">{p.tender.tender_id}</span> <span className="saved-state">{dirty?t.dirty:t.clean}</span></>:t.startDesc}</p></div><div className="load-actions"><button className="primary" onClick={sample} disabled={busy||generating}><Files size={18}/>{t.sample}</button><label className={'button '+(busy||generating?'disabled':'')}><Upload size={18}/>{t.import}<input data-testid="requirements-input" type="file" accept=".json,application/json" disabled={busy||generating} onChange={e=>{const f=e.target.files?.[0];if(f)void importJSON(f);e.target.value='';}}/></label></div></section>
 {messages.length>0&&<section className="messages" aria-live="polite">{messages.map((m,i)=><div key={i} className="message"><AlertTriangle size={17}/><span>{m.name&&<strong>{m.name}: </strong>}{t[m.key]}</span><button aria-label={t.dismiss} onClick={()=>setMessages(ms=>ms.filter((_,n)=>n!==i))}><X size={16}/></button></div>)}</section>}
 {busy&&<p className="loading" role="status">{t.busy}</p>}
 {!p?<section className="empty-start"><div className="illustration"><FileText size={55}/><span><CheckCircle2 size={25}/></span></div><div className="empty-step"><b>1</b><h2>{t.load}</h2><p>{t.import}</p></div><ArrowRight className="empty-arrow"/><div className="empty-step"><b>2</b><h2>{t.check}</h2><p>{t.requirements}</p></div><ArrowRight className="empty-arrow"/><div className="empty-step"><b>3</b><h2>{t.download}</h2><p>{t.generate}</p></div></section>:<>
 <section className="tender-meta"><div><span>{t.entity}</span><strong>{p.tender.procuring_entity}</strong></div><div><span>{t.bidder}</span><strong>{p.tender.bidder}</strong></div><div><span>{t.deadline}</span><strong>{p.tender.submission_deadline}</strong></div></section>
 <div className="work-grid"><section className="panel checklist" id="checklist"><div className="panel-heading"><div><h2>{t.requirements}</h2><p>{p.requirements.length} {t.included.toLowerCase()} · {counts.OK}/{p.requirements.length} {t.ok}</p></div><span className="count-pill">{p.requirements.length}</span></div><div className="progress" role="progressbar" aria-label={t.progress} aria-valuemin={0} aria-valuemax={p.requirements.length} aria-valuenow={counts.OK}><div style={{width:counts.OK/p.requirements.length*100+'%'}}/></div>
 <div className="status-overview">{(['OK','Missing','Expiry date needed','Expired','Not provided'] as Status[]).map(s=><span key={s} className={'status '+statusClass(s)}><b data-status-count={s}>{counts[s]}</b> {t[s]}</span>)}</div>
 {p.requirements.map(r=>{const a=p.assignments[r.id],f=p.files.find(f=>f.id===a?.fileId),status=getRequirementStatus(r,a,p.tender.submission_deadline),suggestions=suggestMatches(p,r);return <article key={r.id} className="requirement" data-requirement={r.id}><div className="requirement-title"><span className="order">{String(r.order).padStart(2,'0')}</span><div><h3>{lang==='bn'?r.title_bn:r.title_en}</h3><span className={'requirement-kind '+(r.mandatory?'required':'')}>{r.mandatory?t.mandatory:t.optional}</span></div><span className={'status '+statusClass(status)}>{status==='OK'?<CheckCircle2 size={13}/>:status==='Not provided'?null:<AlertTriangle size={13}/>} {t[status]}</span></div><div className="match-fields"><label><span>{t.files}</span><select aria-label={`${lang==='bn'?r.title_bn:r.title_en} — ${t.files}`} data-match={r.id} value={a?.fileId||''} disabled={busy||generating} onChange={e=>match(r.id,e.target.value)}><option value="">{t.noMatch}</option>{p.files.map(file=><option key={file.id} value={file.id} disabled={!canAssign(p,r.id,file.id)}>{file.name} · {file.pageCount} {t.pages}{duplicateIds.has(file.id)?' · '+t.duplicate:''}</option>)}</select></label>{f&&r.has_expiry&&<label className="expiry-field"><span>{t.expiry}</span><input type="date" data-expiry={r.id} aria-label={`${lang==='bn'?r.title_bn:r.title_en} — ${t.expiry}`} value={a.expiryDate} disabled={generating||busy} onChange={e=>change({...p,assignments:{...p.assignments,[r.id]:{...a,expiryDate:e.target.value}}})}/></label>}{f&&<button className="icon-button" title={t.preview} aria-label={`${t.preview} ${f.name}`} onClick={()=>setPreview({bytes:f.bytes,name:f.name})}><Eye size={18}/></button>}</div>{!f&&suggestions.length>0&&<details className="suggestions"><summary><Sparkles size={13}/> {t.suggestions} ({suggestions.length})</summary><p>{t.suggestionHint}</p>{suggestions.map(({f})=><div className="suggestion" key={f.id}><span>{f.name}</span><button disabled={busy||generating} onClick={()=>match(r.id,f.id)}>{t.accept}</button></div>)}</details>}</article>;})}</section>
 <aside><section className="panel upload-panel"><div className="panel-heading"><h2>{t.files}</h2><span className="count-pill">{p.files.length}/30</span></div><label className={'upload-zone '+(busy||generating?'disabled':'')}><Upload size={28}/><strong>{t.upload}</strong><span>{t.limits}</span><input data-testid="pdf-input" type="file" multiple accept=".pdf,application/pdf" disabled={busy||generating} onChange={e=>{const files=Array.from(e.target.files||[]);if(files.length)void ingest(files,p);e.target.value='';}}/></label><div className="storage-meter"><span>{(p.files.reduce((a,f)=>a+f.byteLength,0)/1e6).toFixed(2)} / 50 MB</span></div>{!p.files.length?<p className="empty-files">{t.emptyFiles}</p>:<ul className="file-list">{p.files.map(f=><li key={f.id} className={duplicateIds.has(f.id)?'is-duplicate':''}><FileText size={19}/><div><strong>{f.name}</strong><span>{f.pageCount} {t.pages}{duplicateIds.has(f.id)&&<em>{t.duplicate}</em>}</span></div><button className="icon-button" aria-label={`${t.preview} ${f.name}`} onClick={()=>setPreview({bytes:f.bytes,name:f.name})}><Eye size={16}/></button><button disabled={busy||generating} className="icon-button" aria-label={`${t.remove} ${f.name}`} onClick={()=>change(removeFile(p,f.id))}><Trash2 size={16}/></button></li>)}</ul>}{duplicates.length>0&&<p className="duplicate-note"><AlertTriangle size={16}/>{t.duplicateHint}</p>}</section>
 <section className="panel summary-panel"><div className="panel-heading"><h2>{t.summary}</h2>{!blocked.length&&<CheckCircle2 className="teal" size={21}/>}</div><dl className="metrics"><div><dt>{t.included}</dt><dd>{selected.length}</dd></div><div><dt>{t.sourcePages}</dt><dd>{selected.reduce((a,{f})=>a+f.pageCount,0)}</dd></div><div><dt>{t.packagePages}</dt><dd>{totalPages(p)}</dd></div></dl><label className="checkbox"><input type="checkbox" checked={p.options.index} disabled={busy||generating} onChange={e=>change({...p,options:{...p.options,index:e.target.checked,stamp:p.options.stamp?{...p.options.stamp,pages:''}:undefined}})}/>{t.index}</label><div className={'readiness '+(blocked.length?'blocked':'ready')}><strong>{blocked.length?t.blocked:t.ready}</strong>{blocked.length>0&&<ul>{blocked.map(r=><li key={r.id}>{lang==='bn'?r.title_bn:r.title_en}: {t[getRequirementStatus(r,p.assignments[r.id],p.tender.submission_deadline)]}</li>)}</ul>}{stampError&&<p role="alert">{stampError}</p>}</div><button data-testid="generate" className="primary generate" disabled={!!blocked.length||busy||generating||!!stampError} onClick={()=>void generate()}><Download size={18}/>{generating?t.generating:t.generate}</button><button className="full" disabled={!!blocked.length||busy||generating||!!stampError} onClick={()=>void generate(true)}><Eye size={16}/>{t.previewPackage}</button><button className="full subtle" disabled={busy||generating} onClick={()=>downloadBytes(exportChecklist(p,lang,s=>t[s]),p.tender.tender_id+'_Checklist.csv','text/csv;charset=utf-8')}><Download size={16}/>{t.csv}</button></section>
 <section className="panel bonus-panel"><details><summary><FileText size={17}/>{t.stamp}</summary><p>{t.stampHint}</p><label className="button stamp-upload"><Upload size={16}/>{t.stampUpload}<input type="file" accept="image/png,.png" disabled={busy||generating} onChange={e=>{const f=e.target.files?.[0];if(f)void stamp(f);e.target.value='';}}/></label>{p.options.stamp&&<div className="stamp-controls"><label>{t.stampPages}<input data-testid="stamp-pages" value={p.options.stamp.pages} onChange={e=>updateStamp({pages:e.target.value})}/></label><label>{t.position}<select value={p.options.stamp.position} onChange={e=>updateStamp({position:e.target.value as Stamp['position']})}><option value="bottom-right">{t.bottomRight}</option><option value="bottom-left">{t.bottomLeft}</option><option value="top-right">{t.topRight}</option><option value="custom">{t.custom}</option></select></label>{(['width','x','y'] as const).map(k=><label key={k}>{t[k]}<input type="number" min={k==='width'?20:0} max={2000} value={p.options.stamp![k]} onChange={e=>updateStamp({[k]:Math.max(k==='width'?20:0,Math.min(2000,Number(e.target.value)||0))})}/></label>)}<button onClick={()=>change({...p,options:{...p.options,stamp:undefined}})}>{t.clearStamp}</button></div>}</details></section>
 <section className="panel bonus-panel"><details><summary><Sparkles size={17}/>{t.ai}</summary><p>{t.aiInfo}</p><label>{t.key}<input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t.consent}</label><button onClick={()=>void askAI()} disabled={aiBusy}>{t.askAI}</button>{aiBusy&&<button onClick={()=>abort.current?.abort()}>{t.cancel}</button>}{aiText&&<div className="ai-result"><strong>{t.aiLabel}</strong><p>{aiText}</p></div>}<p className="muted">{t.aiNotVerified}</p></details></section></aside></div></>}
 <footer><ShieldCheck size={15}/>{t.footer}</footer></main>{preview&&<Preview bytes={preview.bytes} name={preview.name} t={t} onClose={()=>setPreview(null)}/>}</>;
}
