import { PDFDocument, StandardFonts, rgb, degrees, PDFName } from 'pdf-lib';
import * as pdfjs from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import {getBlockingIssues,pageLayout,indexPageCount,parsePages,totalPages,validateProject,type Project,type DocumentFile} from './domain';
pdfjs.GlobalWorkerOptions.workerSrc=worker;
export async function inspectPdf(file:File):Promise<DocumentFile>{
 const bytes=new Uint8Array(await file.arrayBuffer());
 if(!/\.pdf$/i.test(file.name)||!new TextDecoder().decode(bytes.slice(0,1024)).includes('%PDF-'))throw Error('notPDF');
 try{const doc=await PDFDocument.load(bytes,{updateMetadata:false});if(doc.isEncrypted)throw Error('encrypted');if(doc.getPageCount()<1)throw Error('badPDF');
 const check=await pdfjs.getDocument({data:bytes.slice(),isEvalSupported:false}).promise;const pageCount=check.numPages;await check.destroy();
 const hash=await crypto.subtle.digest('SHA-256',bytes);return {id:crypto.randomUUID(),name:file.name,bytes,byteLength:bytes.length,pageCount,sha256:[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')};
 }catch(e){if(e instanceof Error&&(/password|encrypted/i.test(e.message)||e.name==='PasswordException'))throw Error('encrypted');throw Error('badPDF');}
}
export async function renderPreview(bytes:Uint8Array,pageNumber:number,canvas:HTMLCanvasElement,maxWidth=900){const doc=await pdfjs.getDocument({data:bytes.slice(),isEvalSupported:false}).promise;try{const page=await doc.getPage(pageNumber);const base=page.getViewport({scale:1});const viewport=page.getViewport({scale:Math.min(maxWidth/base.width,2)});canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvas,canvasContext:canvas.getContext('2d')!,viewport}).promise;return doc.numPages;}finally{await doc.destroy();}}
function wrap(text:string,measure:(s:string)=>number,max:number){const out:string[]=[];for(const para of text.split('\n')){let line='';for(const word of para.split(/\s+/)){if(measure(line?line+' '+word:word)>max&&line){out.push(line);line='';}if(measure(word)>max){for(const c of word){if(measure(line+c)>max){out.push(line);line='';}line+=c;}}else line+=(line?' ':'')+word;}out.push(line);}return out;}
async function textImage(text:string,size:number,max:number,color='#18333f'){
 await document.fonts.load(`${size}px "Noto Sans Bengali"`);
 const c=document.createElement('canvas'),ctx=c.getContext('2d')!;ctx.font=`${size}px "Noto Sans Bengali", sans-serif`;const lines=wrap(text,s=>ctx.measureText(s).width,max);const lineHeight=size*1.65;const height=Math.ceil(lines.length*lineHeight+size*.5);c.width=Math.ceil(max*3);c.height=height*3;ctx.scale(3,3);ctx.font=`${size}px "Noto Sans Bengali", sans-serif`;ctx.fillStyle=color;ctx.textBaseline='top';lines.forEach((s,i)=>ctx.fillText(s,0,i*lineHeight));return {bytes:await (await fetch(c.toDataURL('image/png'))).arrayBuffer(),height,width:max};
}
export async function buildPackage(raw:Project):Promise<Uint8Array>{
 const p=validateProject(raw);if(getBlockingIssues(p).length)throw Error('blocked');
 const target=await PDFDocument.create(),font=await target.embedFont(StandardFonts.Helvetica),bold=await target.embedFont(StandardFonts.HelveticaBold);const navy=rgb(.08,.18,.24),teal=rgb(.04,.43,.38);const layout=pageLayout(p);const margin=44,width=595,contentWidth=width-margin*2;
 const drawText=async(page:ReturnType<PDFDocument['addPage']>,text:string,x:number,y:number,size=11,max=contentWidth,isBold=false)=>{if(/[^\x20-\x7e\n]/.test(text)){const image=await textImage(text,size,max);const embedded=await target.embedPng(image.bytes);page.drawImage(embedded,{x,y:y-image.height,width:max,height:image.height});return image.height;}const f=isBold?bold:font,lines=wrap(text,s=>f.widthOfTextAtSize(s,size),max);lines.forEach((line,i)=>page.drawText(line,{x,y:y-size-i*size*1.5,size,font:f,color:navy}));return lines.length*size*1.5;};
 const coverLines=[['Tender ID',p.tender.tender_id],['Tender title',p.tender.title],['Procuring entity',p.tender.procuring_entity],['Bidder',p.tender.bidder],['Submission deadline',p.tender.submission_deadline],['Package generated',new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())]];
 const estimatedText=(s:string,size:number)=>wrap(s,t=>/[^\x20-\x7e]/.test(t)?t.length*size:font.widthOfTextAtSize(t,size),contentWidth).length*size*1.8;
 const coverHeight=Math.max(842,240+coverLines.reduce((a,[label,value])=>a+20+estimatedText(label+': '+value,12),0)+layout.reduce((a,{r,f})=>a+10+estimatedText(r.title_en+' — '+f.name,11),0));
 const cover=target.addPage([width,coverHeight]);cover.drawRectangle({x:0,y:coverHeight-14,width,height:14,color:teal});let cy=coverHeight-60;cy-=await drawText(cover,'TENDER DOCUMENT PACKAGE',margin,cy,21,contentWidth,true);cy-=35;
 for(const [label,value] of coverLines){cy-=await drawText(cover,label.toUpperCase(),margin,cy,9,contentWidth,true);cy-=5;cy-=await drawText(cover,value,margin,cy,12);cy-=18;}
 cy-=15;cy-=await drawText(cover,'INCLUDED DOCUMENTS · IN REQUIRED ORDER',margin,cy,12,contentWidth,true);cy-=16;
 for(const {r,f} of layout){cy-=await drawText(cover,`${r.order}. ${r.title_en} — ${f.name}`,margin,cy,11);cy-=10;}
 if(p.options.index){for(let i=0;i<indexPageCount(p);i++){const rows=layout.slice(i*12,i*12+12);const rowHeights=await Promise.all(rows.map(async({r,f})=>Math.max(55,estimatedText(r.title_en,11)+ (await textImage(r.title_bn,12,420)).height+estimatedText(f.name,8)+12)));const height=Math.max(842,155+rowHeights.reduce((a,b)=>a+b,0));const page=target.addPage([width,height]);let y=height-50;y-=await drawText(page,'DOCUMENT INDEX',margin,y,20,contentWidth,true);y-=await drawText(page,'নথির সূচি',margin,y-10,16);y-=28;
 for(let j=0;j<rows.length;j++){const {r,f,start}=rows[j];page.drawLine({start:{x:margin,y:y+5},end:{x:width-margin,y:y+5},thickness:.5,color:rgb(.8,.85,.86)});let rowY=y;rowY-=await drawText(page,r.title_en,margin,rowY,11,420,true);rowY-=await drawText(page,r.title_bn,margin,rowY-2,12,420);await drawText(page,f.name,margin,rowY-3,8,420);page.drawText(String(start),{x:width-margin-22,y:y-12,size:12,font:bold,color:teal});y-=rowHeights[j];}
 }}
 for(const {f} of layout){const source=await PDFDocument.load(f.bytes,{updateMetadata:false});let renderDoc:pdfjs.PDFDocumentProxy|undefined;
 try{for(let n=0;n<source.getPageCount();n++){const src=source.getPage(n),box=src.getCropBox(),rotation=((src.getRotation().angle%360)+360)%360;const swapped=rotation===90||rotation===270;const w=swapped?box.height:box.width,h=swapped?box.width:box.height;const dest=target.addPage([w,h+36]);
 const annotations=src.node.get(PDFName.of('Annots'));if(annotations){renderDoc??=await pdfjs.getDocument({data:f.bytes.slice(),isEvalSupported:false}).promise;const page=await renderDoc.getPage(n+1),viewport=page.getViewport({scale:2});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvas,canvasContext:canvas.getContext('2d')!,viewport,annotationMode:pdfjs.AnnotationMode.ENABLE}).promise;const image=await target.embedPng(await (await fetch(canvas.toDataURL())).arrayBuffer());dest.drawImage(image,{x:0,y:36,width:w,height:h});
 }else{const embedded=await target.embedPage(src,{left:box.x,bottom:box.y,right:box.x+box.width,top:box.y+box.height});const pos=rotation===90?{x:0,y:36+box.width}:rotation===180?{x:box.width,y:36+box.height}:rotation===270?{x:box.height,y:36}:{x:0,y:36};dest.drawPage(embedded,{...pos,width:box.width,height:box.height,rotate:degrees(-rotation)});}
 }}finally{await renderDoc?.destroy();}}
 if(p.options.stamp){const stamp=p.options.stamp,selected=parsePages(stamp.pages,totalPages(p));if(!selected.length)throw Error('noStampPages');const image=await target.embedPng(stamp.bytes);for(const n of selected){const page=target.getPage(n-1),{width:w,height:h}=page.getSize();const sw=Math.min(Math.max(stamp.width,20),w-24),sh=Math.min(sw*image.height/image.width,h-60);let x=stamp.x,y=36+stamp.y;if(stamp.position==='bottom-right')x=w-sw-24;if(stamp.position==='bottom-left')x=24;if(stamp.position==='top-right'){x=w-sw-24;y=h-sh-24;}page.drawImage(image,{x:Math.max(0,Math.min(x,w-sw)),y:Math.max(36,Math.min(y,h-sh)),width:sw,height:sh});}}
 const pages=target.getPages();pages.forEach((page,i)=>{const w=page.getWidth();page.drawRectangle({x:0,y:0,width:w,height:36,color:rgb(.96,.98,.98)});const text=`${p.tender.tender_id} | Page ${i+1} of ${pages.length}`;if(/[^\x20-\x7e]/.test(text))return;const size=Math.min(9,(w-20)/font.widthOfTextAtSize(text,1));page.drawText(text,{x:(w-font.widthOfTextAtSize(text,size))/2,y:13,size,font,color:navy});});
 // Tender identifiers with non-Latin glyphs use browser shaping in the same reserved band.
 if(/[^\x20-\x7e]/.test(p.tender.tender_id))for(let i=0;i<pages.length;i++)await drawText(pages[i],`${p.tender.tender_id} | Page ${i+1} of ${pages.length}`,12,30,9,pages[i].getWidth()-24);
 target.setTitle(`${p.tender.tender_id} Tender Document Package`);target.setCreator('TenderReady — browser-only');return target.save();
}
export function downloadBytes(bytes:Uint8Array|string,name:string,type:string){const blob=new Blob([typeof bytes==='string'?bytes:new Uint8Array(bytes).buffer],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
